name: Automatisation Josue 1-8

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # On monte d'un cran pour la stabilité

      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install google-genai twilio requests

      - name: Execution du Bot Josué
        env:
          BOT_GEMINI_KEY: ${{ secrets.BOT_GEMINI_KEY }}
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          TWILIO_NUMBER: ${{ secrets.TWILIO_NUMBER }}
          TARGET_NUMBER: ${{ secrets.TARGET_NUMBER }}
        run: python bot_josue.py
